databases:
  - name: tutor-plus
    databaseName: tutor-plus
    user: tutor-plus

services:
  - type: web
    name: tutor-plus
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutor-plus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
